-- 코드를 입력하세요
SELECT  DISTINCT A1.ANIMAL_ID, A1.NAME, A1.DATETIME
FROM  ANIMAL_INS A1, ANIMAL_INS A2
WHERE A1.ANIMAL_ID = A2.ANIMAL_ID
ORDER BY NAME  ASC, (CASE WHEN  A1.ANIMAL_ID = A2.ANIMAL_ID THEN A1.DATETIME END) DESC;

